FROM arm64v8/debian:trixie
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    build-essential cmake ccache \
    qt6-base-dev qt6-declarative-dev \
    qt6-serialbus-dev qt6-serialport-dev \
    libgl1-mesa-dev libxkbcommon-dev \
    qml6-module-qtquick \
    qml6-module-qtquick-controls \
    qml6-module-qtquick-layouts \
    qml6-module-qtquick-window \
    qml6-module-qtquick-templates \
    qml6-module-qtquick-shapes \
    qml6-module-qtqml-workerscript \
    file \
  && rm -rf /var/lib/apt/lists/*
